spring:
    # ???
    datasource:
        url: jdbc:mysql://localhost:3306/news_release_system?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
